# https://github.com/dbcls/visc/blob/main/variant-rdf-spec/SNP/mono_allelic/rs1570391677_snv.ttl

- VariantSNV [], <https://togovar.biosciencedbc.jp/variant/tgv66423707>:
  - a: gvo:SNV
  - rdfs:subClassOf:
    - subclass: obo:SO_0001483  # SNV
  - dct:identifier:
    - id: "rs1570391677"  # $ID or {"name": "dbSNP", "indentifier": "rs1570391677"}
  # REF
  - gvo:ref:  # gvo:ref or sio:SIO_000223 (has property)
    - []:
      - a: gvo:ReferenceFeature
      - rdfs:subClassOf:
        - ref_subclass: obo:SO_0001236  # base
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:ExactPosition
          - faldo:position:
            - ref_position: 10001
          - faldo:reference:
            - ref_reference: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - ref_allele: "T"
  # ALT
  - gvo:alt:  # gvo:alt or sio:SIO_000223 (has property)
    - []:
      - a: gvo:AlternativeFeature 
      - rdfs:subClassOf:
        - alt_subclass: obo:SO_0001236
      - faldo:location:
        - []:  # or sio:SIO_000061 (is located in)
          - a: faldo:ExactPosition
          - faldo:position:
            - alt_position: 10001
          - faldo:reference:
            - alt_reference: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - alt_allele: "A"
  # INFO
  - gvo:qual:
    - qual: "."
  - gvo:filter:
    - filter: "."
  - gvo:info:
    - []:
      - rdf:label:
        - info_label: "VC"
      - sio:SIO_000300:  # has value or sio:SIO_000223 (has property)?
        - info_value: "SNV"

