# https://github.com/dbcls/visc/blob/main/variant-rdf-spec/SNP/mono_allelic/rs1322538365_ins.ttl

- VariantIns []:
  - a: gvo:Insertion
  - rdfs:subClassOf:
    - subclass: obo:SO_0000667  # insertion
  - dct:identifier:
    - id: "rs1322538365"
  # Normalized REF
  - gvo:ref:  # gvo:ref or sio:SIO_000223 (has property)
    - []:
      - a: gvo:NormalizedReferenceFeature
      - rdfs:subClassOf:
        - ref_subclass: obo:SO_0000366  # insertion_site
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:InBetweenPosition
          - faldo:after:
            - ref_after: 10108
          - faldo:before:
            - ref_before: 10109
          - faldo:reference:
            - ref_reference: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - ref_allele: ""
  # Normalized ALT
  - gvo:alt:
    - []:
      - a: gvo:NormalizedAlternativeFeature
      - rdfs:subClassOf:
        - alt_subclass: obo:SO_0000667  # insertion
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:InBetweenPosition
          - faldo:after:
            - alt_after: 10108
          - faldo:before:
            - alt_before: 10109
          - faldo:reference:
            - alt_reference: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - alt_allele: "T"
  # REF
  - gvo:orig_ref:  # gvo:ref or sio:SIO_000223 (has property)
    - []:
      - a: gvo:ReferenceFeature
      - rdfs:subClassOf:
        - orig_ref_subclass: obo:SO_0001236  # base
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:ExactPosition
          - faldo:position:
            - orig_ref_position:  10008
          - faldo:reference:
            - orig_ref_referene: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - orig_ref_allele: "C"
  # ALT
  - gvo:orig_alt:  # gvo:alt or sio:SIO_000223 (has property)
    - []:
      - a: gvo:AlternativeFeature
      - rdfs:subClassOf:
        - orig_alt_sublass: obo:SO_0000667  # insertion
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:ExactPosition
          - faldo:position:
            - orig_alt_position: 10008
          - faldo:reference:
            - orig_alt_reference: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - orig_alt_allele: "CT"
  # INFO
  - gvo:qual:
    - info_qual: "."
  - gvo:filter:
    - info_filter: "."
  - gvo:info:
    - []:
      - rdf:label:
        - info_label: "VC"
      - sio:SIO_000300:  # gvo:info sio:SIO_000223 (has property)
        - info_value: "INS"

