# https://github.com/dbcls/visc/blob/main/variant-rdf-spec/SNP/mono_allelic/rs1553123056_indel.ttl

- VariantIndel []:
  - a: gvo:INDEL
  - rdfs:subClassOf:
    - subclass: obo:SO_1000032  # delins
  - dct:identifier:
    - id: "rs1553123056"
  # Normalized REF
  - gvo:ref:  # gvo:ref or sio:SIO_000223 (has property)
    - []:
      - a: gvo:NormalizedReferenceFeature
      - rdfs:subClassOf:
        - ref_subclass: obo:SO_0000366, obo:SO_0000159  # insertion_site, deletion_junction
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:InBetweenPosition
          - faldo:after:
            - ref_after: 83119
          - faldo:before:
            - ref_before: 83121
          - faldo:reference:
            - ref_reference: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - ref_allele: "A"
  # Normalized ALT
  - gvo:alt:
    - []:
      - a: gvo:NormalizedAlternativeFeature
      - rdfs:subClassOf:
        - alt_subclass: obo:SO_1000032, obo:SO_0000366, obo:SO_0000159  # delins, insertion_site, deletion_junction
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:InBetweenPosition
          - faldo:after:
            - alt_after: 83119
          - faldo:before:
            - alt_before: 83121
          - faldo:reference:
            - alt_reference: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - alt_allele: "TAAC"
  # REF
  - gvo:orig_ref:  # gvo:ref or sio:SIO_000223 (has property)
    - []:
      - a: gvo:ReferenceFeature
      - rdfs:subClassOf:
        - orig_ref_subclass: obo:SO_0000001  # region
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:Region
          - faldo:begin:
            - orig_ref_begin: 83119
          - faldo:end:
            - orig_ref_end: 83120
          - faldo:reference:
            - orig_ref_referene: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - orig_ref_allele: "AA"
  # ALT
  - gvo:orig_alt:  # gvo:alt or sio:SIO_000223 (has property)
    - []:
      - a: gvo:AlternativeFeature
      - rdfs:subClassOf:
        - orig_alt_sublass: obo:SO_0000001  # region
      - faldo:location:  # or sio:SIO_000061 (is located in)
        - []:
          - a: faldo:Region
          - faldo:begin:
            - orig_alt_begin: 83119
          - faldo:end:
            - orig_alt_end: 83120
          - faldo:reference:
            - orig_alt_reference: hco:1\/GRCh37
      - sio:SIO_000300:  # has value
        - orig_alt_allele: "ATAAC"
  # INFO
  - gvo:qual:
    - info_qual: "."
  - gvo:filter:
    - info_filter: "."
  - gvo:info:
    - []:
      - rdf:label:
        - info_label: "VC"
      - sio:SIO_000300:  # gvo:info sio:SIO_000223 (has property)
        - info_value: "INDEL"

